version: '3'

services:
  postgres:
    image: "postgres:14.0"
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: catelog_db
      POSTGRES_PASSWORD: catelog_db_password
      POSTGRES_DB: catelog_service
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/